use_frameworks!

platform :ios, '10.0'

target 'Odeum_Example' do
  use_frameworks!
  pod 'Odeum', :path => '../'

  target 'Odeum_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 3.0.0'
    pod 'Nimble', '~> 9.0.0'
  end
end
